### ISSUE TITLE
Dockerfile ignores

### ISSUE THREAD

**Issue by jhmartin** [AlexRudd/key-manager#6]
What is the purpose of the .dockerignore contents? When trying to build this with jenkins I get errors about ca-certificates.pem not existing (even if it is present in the workdir), and an explicit complaint that the .dockerignore file includes Dockerfile.

**Comment by alexrudd** [comment]
Hi,

The docker ignore file is used to determine what context is passed to the docker daemon at build time. The contents of the .dockerignore file are:

```
*
!_bin
!ca-certificates.crt
```
The first line is a catch all, as the majority of the repos content doesn't need to be send to the daemon. The next two lines are exceptions to this catch all (starting with '!'). So all that should be passed to the Docker daemon is the `ca-certificates.crt`and the contents of `_bin` (the key-manager executable).

The reason you might be seeing the error regarding `ca-certificates.crt` is because it is not actually part of the repo, but is downloaded by the Makefile at build time, and if you're not using the Makefile then it would still be missing.

The other error regarding the Dockerfile being ignored, I've never seen that before. I always assumed that the Dockerfile wouldn't need to be part of the build context. What version of Docker is your Jenkins server using and can you give me anymore details?

Thanks
Alex

**Comment by alexrudd** [comment]
Assuming this is resolved and closing.
